// <auto-generated />
using Ateliware.Server.Repository.Context;
using Ateliware.Shared.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Ateliware.Server.Migrations
{
    [DbContext(typeof(AteliwareContext))]
    [Migration("20180526035102_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ateliware.Server.Entities.Repository", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id");

                    b.Property<int>("Language");

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Guid");

                    b.ToTable("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
